development:
  adapter: postgresql
  encoding: unicode
  database: Todo
  pool: 5
  username: postgres
  password: digitalogo

test:
  adapter: postgresql
  encoding: unicode
  database: Todo
  pool: 5
  username: postgres
  password: digitalogo

production:
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password: digitalogo
  database: Todo
  schema_search_path: public
  encoding: utf8